### ISSUE TITLE
ReferenceError: MediaPlayer is not defined

### ISSUE THREAD

**Issue by NoLogicAlan** [ShadowLp174/revoice.js#1]
```
/home/runner/SeveralDullConnections/index.js:6
  const media = new MediaPlayer();
                ^

ReferenceError: MediaPlayer is not defined
    at EventEmitter.<anonymous> (/home/runner/SeveralDullConnections/index.js:6:17)
    at EventEmitter.emit (node:events:390:28)
    at EventEmitter.emit (node:domain:475:12)
    at Revoice.emit (/home/runner/SeveralDullConnections/node_modules/revoice.js/Revoice.js:68:30)
    at Revoice.initTransports (/home/runner/SeveralDullConnections/node_modules/revoice.js/Revoice.js:99:10)
    at EventEmitter.<anonymous> (/home/runner/SeveralDullConnections/node_modules/revoice.js/Revoice.js:58:12)
    at EventEmitter.emit (node:events:390:28)
    at EventEmitter.emit (node:domain:475:12)
    at Signaling.processWS (/home/runner/SeveralDullConnections/node_modules/revoice.js/Signaling.js:64:27)
repl process died unexpectedly: exit status 1
```

**Comment by ShadowLp174** [comment]
I'm sorry, the README is wrong...

Just change

```JavaScript
const { Revoice, Media } = require("revoice.js");
```

To:

```JavaScript
const { Revoice, MediaPlayer } = require("revoice.js");
```

I'm sorry, I'll update the readme right now

**Comment by NoLogicAlan** [comment]
> I'm sorry, the README is wrong...
> 
> Just change
> 
> ```js
> const { Revoice, Media } = require("revoice.js");
> ```
> 
> To:
> 
> ```js
> const { Revoice, MediaPlayer } = require("revoice.js");
> ```
> 
> I'm sorry, I'll update the readme right now

```
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: spawn ffmpeg ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
    at onErrorNT (node:internal/child_process:477:16) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn ffmpeg',
  path: 'ffmpeg',
  spawnargs: [
    '-re',
    '-i',
    '-',
    '-map',
    '0:a',
    '-b:a',
    '48k',
    '-maxrate',
    '48k',
    '-c:a',
    'libopus',
    '-f',
    'rtp',
    'rtp://127.0.0.1:5030'
  ]
}
```

**Comment by ShadowLp174** [comment]
It seems that you didn't install ffmpeg... If you have installed it properly then please restart your computer.

I know this is an annoying step and I'll remove this ffmpeg depency in one of the next updates :)

**Comment by NoLogicAlan** [comment]
I did everything and I still have the same error :(.

**Comment by ShadowLp174** [comment]
Did you add ffmpeg to the PATH environment variable?

**Comment by NoLogicAlan** [comment]
idk any examples

**Comment by ShadowLp174** [comment]
k nice :D

There will be a big update anyway as soon as I get ffmpeg's RTP output stream working, and it will switch to pre-shipped ffmpeg binaries and remove problems with pause/resume
